### ISSUE TITLE
Sprint 2: Build A Static Version in React

### ISSUE THREAD

**Issue by matthall8** [FACN4/week9-the-a-team#15]
**- Objective:** Build a static version of the page in react
**- Actions:**
- [x] Agree on File structure #10
- [x] Build static header #11
- [x] Build static choose your players page #12
- [x] Build static game page (with board and notes and crosses) #13 
- [x] Build static winner page (who won and who drew) #14 
- [ ] Continue building logic #17 
- [x] Update App.js with the structure #19 

**Based on** 

### Step 2: https://reactjs.org/docs/thinking-in-react.html

Now that you have your component hierarchy, it’s time to implement your app. The easiest way is to build a version that takes your data model and renders the UI but has no interactivity. It’s best to decouple these processes because building a static version requires a lot of typing and no thinking, and adding interactivity requires a lot of thinking and not a lot of typing. We’ll see why.

To build a static version of your app that renders your data model, you’ll want to build components that reuse other components and pass data using props. props are a way of passing data from parent to child. If you’re familiar with the concept of state, don’t use state at all to build this static version. State is reserved only for interactivity, that is, data that changes over time. Since this is a static version of the app, you don’t need it.

You can build top-down or bottom-up. That is, you can either start with building the components higher up in the hierarchy (i.e. starting with FilterableProductTable) or with the ones lower in it (ProductRow). In simpler examples, it’s usually easier to go top-down, and on larger projects, it’s easier to go bottom-up and write tests as you build.

At the end of this step, you’ll have a library of reusable components that render your data model. The components will only have render() methods since this is a static version of your app. The component at the top of the hierarchy (FilterableProductTable) will take your data model as a prop. If you make a change to your underlying data model and call ReactDOM.render() again, the UI will be updated. It’s easy to see how your UI is updated and where to make changes since there’s nothing complicated going on. React’s one-way data flow (also called one-way binding) keeps everything modular and fast.

Simply refer to the React docs if you need help executing this step.
