### ISSUE TITLE
Sprint 1: Planning & Mock-ups

### ISSUE THREAD

**Issue by matthall8** [FACN4/week9-the-a-team#6]
**Stage:** Planning & Mock-ups

**Objective:** To get the project set-up and planning done.

**To-do:**

- [ ] Set-up React #1 
- [ ] Set-up Netilify #2 
- [ ] Develop mock-up on figma #3 
- [ ] Break The UI Into A Component Hierarchy and give them names #4 
- [ ] Base logic for board #5
